services:
  bmqbrkr:
    image: bmqbrkr:latest
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    volumes:
      - ./config:/etc/local/bmq:ro
    hostname: gallifrey
    command: "/usr/local/bin/bmqbrkr /etc/local/bmq"

  bmqtool:
    image: bmqbrkr:latest
    platform: linux/amd64
    build: 
      context: ../..
      dockerfile: docker/Dockerfile
    hostname: earth
    # This "service" will exit immediately. It's OK, this is a
    # container sitting on the same network as the single node, to be started
    # in interactive mode with `docker-compose run`

networks:
  default:
    driver: bridge
